server:
    port: 8080
spring:
    application:
        name: blogs-technology-production
    config:
        import: optional:classpath:.env[.properties]
    datasource:
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://code4fun.id.vn:5432/blogs_prod?currentSchema=blog_dbo2
        username: ${DB_USERNAME}
    flyway:
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://code4fun.id.vn:5432/blogs_prod?currentSchema=blog_dbo2
        user: ${DB_USERNAME}
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
    kafka:
        bootstrap-servers:
            - http://code4fun.id.vn:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            retries: 5
            properties:
                enable.idempotence: true
                max.in.flight.requests.per.connection: 5
                request.timeout.ms: 100
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        host: smtp.gmail.com
        username: translatorvamkv1@gmail.com
        password: lcyhfdfjdhahknmu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
    servlet:
        multipart:
            max-file-size: 25MB
            max-request-size: 25MB
    data:
        redis:
            host: code4fun.id.vn
            port: 6379
            database: 1
            password: tuanbeovn17
            username: default
oauth2:
    authorizedRedirectUris:
        - http://localhost:3000/oauth2/
management:
    endpoints:
        web:
            exposure:
                include: health
    otlp:
        metrics:
            export:
                url: ${OTLP_METRICS_ENDPOINT:http://172.17.0.1:4318/v1/metrics}
                step: 3s
                enabled: true
        tracing:
            endpoint: ${OTLP_TRACES_ENDPOINT:http://172.17.0.1:4318/v1/traces}
    tracing:
        sampling:
            probability: 1.0
        enabled: true
            
# OpenTelemetry configuration
otel:
    resource:
        attributes:
            service.name: ${spring.application.name:blogs-technology-production}
            service.version: 1.0.0
    exporter:
        otlp:
            endpoint: ${OTLP_TRACES_ENDPOINT:http://172.17.0.1:4318}
            protocol: http/protobuf
    endpoint:
        health:
            show-details: always
    health:
        circuitbreakers:
            enabled: true
# Email Sender
email:
    registration-confirmation:
        template: registration-confirmation-en.html
        subject: Registration Confirmation
        from: noreply@pezzie.com
        base-url: https://blogs-be.code4fun.id.vn/api/v1/auth/registrationConfirm?token=%s
    forgot-password-email:
        template: password-forgot.html
        subject: New Password
        from: noreply@pezzie.com
        base-url:

app:
    generate-categories: true
flywaypf:
    active: blog_dbo2

logging:
    config: classpath:logback-spring-prod.xml


outbound:
    identity:
        client-id: 720549923520-qbmtr8g24bptcp90659vh6ffc39j9se6.apps.googleusercontent.com
        client-secret: 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
        redirect-uri: https://blogs.code4fun.id.vn/authenticate

api:
    username: admin
    password: 123456

file:
    upload:
        url: https://minio-be.code4fun.id.vn

notifications:
    event:
        url: https://notifications-be.code4fun.id.vn
jwt:
    expiryMinutes: 60
    expiryDay: 14
    accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
    refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=

resilience4j:
    circuitbreaker:
        configs:
            default:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                failureRateThreshold: 50
                minimumNumberOfCalls: 4
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 6
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: PT30S
        instances:
            uploadMinioProxyCircuitBreaker:
                baseConfig: default
    retry:
        configs:
            default:
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                maxAttempts: 3
                waitDuration: 1000
        instances:
            uploadMinioProxyRetry:
                baseConfig: default
springdoc:
    swagger-ui:
        enabled: false
    api-docs:
        enabled: false